services:
  kafka:
    container_name: kafka
    image: apache/kafka:4.0.0
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093   # NOTA DO FUTURO: Esta linha está mal, mas só aprendi isso num commit à frente...
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:    # Mount configuration file into container's volume.
      - ./docker/mosquitto/mosquitto-no-auth.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883 # Unencrypted, unauthenticated
      #- 1884:1884  # unencrypted, authenticated
      #- 8885:8885  # encrypted, authenticated

  influxdb:
    container_name: influxdb
    ports:
      - '8086:8086'
    image: 'docker.io/influxdb:2.2.0'
    volumes:
      - influxdb-data:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=UA
      - DOCKER_INFLUXDB_INIT_BUCKET=bucket1
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=abc

  mysql:
    container_name: mysql
    ports:
      - '3306:3306'
    image: 'docker.io/mysql:8.0'
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: sql_data
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: admin123

  grafana:
    image: grafana/grafana-oss:8.4.3
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
      - mysql
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - DOCKER_INFLUXDB_INIT_ORG=UA
      - DOCKER_INFLUXDB_INIT_BUCKET=bucket1
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=abc

  spark-master:
    image: bde2020/spark-master:latest
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "7077:7077"

  spark-worker:
    image: bde2020/spark-worker:latest
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - "8081:8081"

  jupyter:
    image: jupyter/pyspark-notebook
    container_name: jupyter
    depends_on:
      - spark-master
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - SPARK_MASTER=spark://spark-master:7077

  telegraf:
    image: telegraf:1.30
    container_name: telegraf
    depends_on:
      - kafka
      - influxdb
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      - HOST_PROC=/rootfs/proc
      - HOST_SYS=/rootfs/sys
      - HOST_ETC=/rootfs/etc
    ports:
      - "8125:8125/udp"
      - "8092:8092/udp"
      - "8094:8094"
    restart: unless-stopped

  quarkus-app:
    container_name: quarkus-app
    build:
      context: ./code-with-quarkus
      dockerfile: Dockerfile.jvm.package
    ports:
      - "8089:8089"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
    restart: unless-stopped

  python-kafka-producer:
    build:
      context: ./python-kafka-producer
      dockerfile: Dockerfile
    depends_on:
      - kafka
    entrypoint: [ "sleep", "infinity" ]
    restart: unless-stopped


volumes:
  mysql-data:
  influxdb-data:
  grafana-data:
